### ISSUE TITLE
Problem with supply causes Network.write freeze

### ISSUE THREAD

**Issue by catan85** [TMRh20/RF24Network#37]
When I have problems with 3.3v (I suspect caused by an USB hard drive connected to my raspberry) the communications stop working and the arduino stop receiving packets. That's normal, but
in this situation, when I try to send a packet using network.write the arduino completely freeze.
In this situation is impossible to reset the module and then the node stay offline forever.

**Comment by TMRh20** [comment]
See http://tmrh20.github.io/RF24/classRF24.html#a2e40fe66d1231a333aa2534e8491f828

**Comment by catan85** [comment]
ok, I'll try that, thanks for your support.
Bye Andrea
