### ISSUE TITLE
Development: RF24Network::read returns wrong size

### ISSUE THREAD

**Issue by erpalma** [TMRh20/RF24Network#49]
On the last dev branch, while sending a zero length payload, the read method returns "The total number of bytes copied into message" plus a 10 bytes offset.

network.write(header,&payload,0);
network.read(header, &payload, sizeof(payload)); --> returns 10

The issue seems to be around line 631 of RF24Network.cpp

**Comment by TMRh20** [comment]
This should be corrected in the latest update.
