### ISSUE TITLE
Dev Merged with Master

### ISSUE THREAD

**Issue by TMRh20** [TMRh20/RF24Network#55]
Ok, so after a long time coming, the dev branch has been merged into the master branch, and the installer updated to master. 

The 'old' version will not be supported, so please report any potential related issues here, or create a new issue if you have identified the issue and have info etc..

The [current RF24Network](https://github.com/TMRh20/RF24Network/tree/master) - Stable and tested 'release candidate'

The [current DEV version](https://github.com/TMRh20/RF24Network/tree/Development) - for additional changes etc.

The ['old' RF24Network](https://github.com/TMRh20/RF24Network/tree/Archived-OriginalUpdated) - Pretty much the original maniacbug code, updated for the optimized RF24 lib

**Comment by n8henrie** [comment]
Woohoo!

**Comment by prophet-roshak** [comment]
Thanks!

2015-08-30 8:46 GMT+03:00 Nathan Henrie <notifications@github.com>:

> Woohoo!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TMRh20/RF24Network/issues/55#issuecomment-136089542>.
>



-- 
С уважением,
Антон Сабадаш.
