### ISSUE TITLE
Creating a new release

### ISSUE THREAD

**Issue by Avamander** [TMRh20/RF24Network#61]
Could you please create a new release so that this library can be submitted to the IDE's library repo?

**Comment by TMRh20** [comment]
Heh, I assumed you were going to be doing RF24Network also, so I did [RF24Network](https://github.com/TMRh20/RF24Network/releases) and [RF24](https://github.com/TMRh20/RF24/releases)  :p

**Comment by Avamander** [comment]
@TMRh20 You have to retag the RF24 library release. The 1.0.0 release has no library.properties tag.

**Comment by TMRh20** [comment]
Not sure I did it entirely correctly, but it should be updated with the properties file. Tagged as v1.01.

**Comment by TMRh20** [comment]
You now have collaborator access to RF24, RF24Network and RF24Mesh. I hope this makes things easier for you, but please do not push any large changes to the branches without discussion. Thanks!
