### ISSUE TITLE
public vs private for frame_queue and RF24Ethernet

### ISSUE THREAD

**Issue by wiredman** [TMRh20/RF24Network#65]
okay, on the platform I'm using if I fail to have the frame_queue declared as public, I get memory reference crashes... I resolved it  by declaring it public.
line 814-818
#if defined (DISABLE_USER_PAYLOADS)
    uint8_t frame_queue[1]; 
#else
    uint8_t frame_queue[MAIN_BUFFER_SIZE];
#endif

**Comment by TMRh20** [comment]
This seems a bit odd, what platform are you using? Is this the case with the basic example files? Any extra info here might help to identify why it does that.

**Comment by wiredman** [comment]
Mips M4K. yes it happened with the basic example files. only reason I can tell is that it was set to private so was compiled as such.
