### ISSUE TITLE
More than 5 levels

### ISSUE THREAD

**Issue by efsantana** [TMRh20/RF24Network#70]
Is it possible to use a different topology and more than 5 levels?

How can one do it?

**Comment by TMRh20** [comment]
Is it possible? Yes.

How?  Read the [datasheet](https://www.nordicsemi.com/chi/content/download/2730/34105/file/nRF24L01_Product_Specification_v2_0.pdf), write the code...

**5 Levels:**
Modify RF24Network ( # of levels is just a software restriction )

**Different topology:** 
Topology is largely manufacturer defined, but can be worked around by managing the timing (as in token ring), and/or using multicast (disable ESB).
