### ISSUE TITLE
Cannot communic Raspberry Pi and Arduino

### ISSUE THREAD

**Issue by sanphandinh** [TMRh20/RF24Network#82]
I use sample code: helloworld_rx for arduino and helloworld_tx for raspberry pi and opposite. But there cannot communic with each other. However I use RF24 library, there communic very good! 
Please help me!

**Comment by wilmsn** [comment]
Hi sanphandinh,

i had the same problems some time ago coursed by wrong wireing.
Finally i used this setup to get it work:

==> Setup raspberry pi <==
/* 
 * Connect like this:
 *  RPI Pin# | RF24L01 Pin# | Signal | color
 *  ---------|--------------|--------|-------
 *     1     |    VCC       | 3V3    | red
 *     6     |    GND       | 0V     | brown
 *    24     |    CSN       | CSN    | yellow
 *    22     |    CE        | CE     | orange
 *    19     |    MOSI      | MOSI   | blue
 *    21     |    MISO      | MISO   | violett
 *    23     |    SCK       | SCK    | green
 */
 
// Setup for GPIO 22 CE and CE0 CSN with SPI Speed @ 8Mhz
RF24 radio(RPI_V2_GPIO_P1_22, BCM2835_SPI_CS0, BCM2835_SPI_SPEED_8MHZ);  

==> setup arduino <==
// The CE Pin
#define RADIO_CE_PIN 10
// The CSN Pin
#define RADIO_CSN_PIN 9
// Usage: radio(CE_pin, CS_pin)
RF24 radio(RADIO_CE_PIN,RADIO_CSN_PIN);

If you want to use my Roundtriptool you will find it here:
https://github.com/wilmsn/sensorhub ==> testtools
