### ISSUE TITLE
RPi2 w/ Ubuntu ARM: undefined reference when trying to build examples_RPi

### ISSUE THREAD

**Issue by hy565** [TMRh20/RF24Network#86]
Hi guys,

I'm running Ubuntu 14.04 UTS on a RPi2, which has some issues with the existing RF24 libraries built for RPi2 on Raspbian.

Same issue as described here:
https://github.com/TMRh20/RF24/issues/239

Examples in the examples_RPi folder fail to compile due to undefined references.

Issue on the main RF24 library has recently been fixed by @mz-fuzzy .

It will be great if the same fixes can be made for the RF24Network library.

Thank you!

**Comment by mz-fuzzy** [comment]
here it is:
0849bee79971a28d78dc000b3ccbeb18e9a7b013

**Comment by hy565** [comment]
Thanks for the quick fix!
